export default {
  en: {
    aboutUs: 'About us',
    hotels: 'About us',
    service: 'Service',
    rooms: 'Rooms',
    blog: 'Blog',
    home: 'Home',
    news: 'News',
    phone: 'Phone',
    adress: 'Address',
    mail: 'Email',
    ourService: 'Our services',
    ourHotels: 'About us',
    more: 'More',
    booking: 'Booking',
    price: 'Price',
    menu: 'Menu',
    manHolds: 'Accommodates people',
    square: 'Square',
    phoneNumber: 'Phone number',
    send: 'Send',
    bron_title: 'Booking',
    name: 'Name',
    successMessage: 'Successfully sent',
    failMessage: 'Not Send',
    breakfastInclude: 'Breakfast included',
    aboutTashkent: 'About Samarkand',
    register: 'Register',
    find: 'Find',
    nationality: 'Nationality',
    enter: 'Enter',
    login: 'Login',
    password: 'Password',
    cabinet: 'Cabinet',
    editData: 'Edit data',
    editPassword: 'Edit password',
    historyBooking: 'History booking',
    dateDepart: 'Date of departure',
    dataArrival: 'Arrival date',
    oldPassword: 'Old password',
    newPassword: 'New password',
    repeatPassword: 'Repeat password',
    changePassword: 'Change password',
    save: 'Save',
    errorLoginText: 'Login or password wrong',
    hotelNotFound: 'Hotel not Found',
    noHistoryTxt: 'No History',
    children: 'Children',
    adult: 'Adult',
    inputDataCorrectlyErrorTxt: 'Enter data correctly',
    toCabinet: 'To cabinet',
    logOut: 'Log out',
    fromDate: 'From date',
    toDate: 'To date',
    bookingCancel: 'Booking abort',
    bookingSuccess: 'Booking success',
    bookingCheck: 'Booking checking',
    contact: 'Contacts',
    bath: 'Sauna',
    conditioner: 'Air conditioner',
    tv: 'Flat screen TV',
    wifi: 'Free Wi-Fi',
    parking: 'Parking',
    swimming: 'Swimming',
    family: 'Family',
  },
  ru: {
    aboutUs: 'О нас',
    hotels: 'О нас',
    service: 'Услуги',
    rooms: 'Комнаты',
    blog: 'Блог',
    home: 'Главная',
    news: 'Новости',
    phone: 'Телефон',
    adress: 'Адрес',
    mail: 'Почта',
    ourService: 'Наши Услуги',
    ourHotels: 'О нас',
    more: 'Подробнее',
    booking: 'Бронировать',
    price: 'Цена',
    menu: 'Меню',
    manHolds: 'Вмещает человек',
    square: 'Площадь',
    phoneNumber: 'Номер телефона',
    send: 'Отправить',
    bron_title: 'Введите данные для бронирование',
    name: 'Имя',
    successMessage: 'Отправлено',
    failMessage: 'Не отправлено',
    breakfastInclude: 'Завтрак включен',
    aboutTashkent: 'О Самарканде',
    register: 'Регистрация',
    find: 'Искать',
    nationality: 'Гражданство',
    enter: 'Вход',
    login: 'Логин',
    password: 'Пароль',
    cabinet: 'Личный кабинет',
    editData: 'Редактирование данных',
    editPassword: 'Смена пароля',
    historyBooking: 'История броней',
    dateDepart: 'Дата выезда',
    dataArrival: 'Дата въезда:',
    oldPassword: 'Старый пароль',
    newPassword: 'Новый пароль',
    repeatPassword: 'Повторите новый пароль',
    changePassword: 'Сменить пароль',
    save: 'Сохранить',
    errorLoginText: 'Пароль или логин неправильно введено',
    hotelNotFound: 'Не найдено',
    noHistoryTxt: 'История отсутствует',
    children: 'Дети',
    adult: 'Взрослие',
    inputDataCorrectlyErrorTxt: 'Введите данные правильно',
    toCabinet: 'В кабинет',
    logOut: 'Выход',
    fromDate: 'От',
    toDate: 'До',
    bookingCancel: 'Бронирования отменено',
    bookingSuccess: 'Успешное бронирование',
    bookingCheck: 'Проверка бронирования',
    contact: 'Контакты',
    bath: 'Ванна',
    conditioner: 'Кондиционер',
    tv: 'Телевизор с плоским экраном',
    wifi: 'Бесплатный Wi-Fi',
    parking: 'Парковка',
    swimming: 'Плавание',
    family: 'Семья',
  },
};
